version: '3'
services:
  db:
    image: postgres:10.4
    ports:
      - 5432:5432
    volumes:
      - ./db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./db/sampledata/:/sampledata/
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db